### PR TITLE
Add check for modified date when harvesting

### PR DESCRIPTION
**Pull request by janette**
connects #2612

## QA Steps
```
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "http://demo.getdkan.com/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [
    {
      "@type": "dcat:Dataset",
      "accessLevel": "public",
      "contactPoint": {
        "fn": "Stefanie Gray",
        "hasEmail": "mailto:stefanie@example.com"
      },
      "description": "harvest modified date as a term",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "https://s3.amazonaws.com/dkan-default-content-files/phpunit/GenChart_0_0.csv",
          "mediaType": "text/csv",
          "format": "csv",
          "description": "<p>Population of state employees broken down into Gen X, Gen Y, Baby Boomers and Over 65+.</p> ",
          "title": "TEST - Workforce By Generation (2011-2015)"
        }
      ],
      "identifier": "95f8eac4-fd1f-4b35-8472-5c87e9425dfa",
      "keyword": [
        "demographics",
        "socioeconomic",
        "workforce"
      ],
      "license": "http://opendefinition.org/licenses/gfdl/",
      "issued": "2016-06-22",
      "modified": "R/P1D",
      "temporal": "2011/2015",
      "publisher": {
        "@type": "org:Organization",
        "name": "TEST - State Economic Council"
      },
      "accrualPeriodicity": "irregular",
      "title": "TEST - dataset 1",
      "dataQuality": true
    },
    {
      "@type": "dcat:Dataset",
      "accessLevel": "public",
      "contactPoint": {
        "fn": "Stefanie Gray",
        "hasEmail": "mailto:stefanie@example.com"
      },
      "description": "No modified or issued dates",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "https://s3.amazonaws.com/dkan-default-content-files/phpunit/2015EligibleVsActual.csv",
          "mediaType": "text/csv",
          "format": "csv",
          "description": "<p>This data, ranging from fiscal year 2011 to fiscal year 2015, depicts the percentage of the workforce that is eligible to retire compared to the percentage of the workforce who actually retired.</p> ",
          "title": "TEST - Retirements: Eligible vs. Actual"
        }
      ],
      "identifier": "11f8eac4-fd1f-4b35-8472-5c87e9425dfa",
      "keyword": [
        "demographics",
        "socioeconomic",
        "workforce"
      ],
      "accrualPeriodicity": "R/P1M",
      "license": "http://opendefinition.org/licenses/gfdl/",
      "temporal": "2011/2015",
      "publisher": {
        "@type": "org:Organization",
        "name": "TEST - State Economic Council"
      },
      "title": "TEST - dataset 2",
      "dataQuality": true
    },
    {
      "@type": "dcat:Dataset",
      "accessLevel": "public",
      "contactPoint": {
        "fn": "Stefanie Gray",
        "hasEmail": "mailto:stefanie@example.com"
      },
      "description": "harvest modified date is date, should save as is",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "https://s3.amazonaws.com/dkan-default-content-files/phpunit/2015EligibleVsActual.csv",
          "mediaType": "text/csv",
          "format": "csv",
          "description": "test"
        }
      ],
      "identifier": "12f8eac4-fd1f-4b35-8472-5c87e9425dfa",
      "license": "http://opendefinition.org/licenses/gfdl/",
      "issued": "2016-06-22",
      "modified": "2016-08-22",
      "temporal": "2011/2015",
      "accrualPeriodicity": "R/P1W",
      "publisher": {
        "@type": "org:Organization",
        "name": "TEST - empty modified value"
      },
      "title": "TEST - dataset 3",
      "dataQuality": true
    }
  ]
}
```
- [ ] Create an endpoint with the above json data using http://myjson.com/
  or https://api.myjson.com/bins/185uo4
- [ ]  Use above url to create a harvest source and harvest
- [ ]  Dataset 1 should have a frequency value of 'Irregularly', modified value of 'Daily'
- [ ]  Dataset 2 should have a frequency value of 'monthly', modified value of today's date
- [ ]  Dataset 3 should have a frequency value of 'weekly', modified value of 2016-08-22

## Reminders

- [ ] There is test for the issue.
- [ ] Coding standards checked.
- [ ] Review docs.getdkan.com (or in /docs) to see if it still covers the scope of the PR and update if needed.

### CODE REVIEW

**Comment by erogray** [comment]
@janette this looks like it uses accrualPeriodicity if it's empty. But I've seen JSON files in which there are periodicity values in both modified and accrualPeriodicity, and the values differ. It's also possible that the intent could differ: accrualPeriodicity may indicate how often the data itself changes, while modified would indicate when/how often the dataset is exported. I'm not sure about this, but I wanted to raise it as a potential problem.

**Comment by janette** [comment]
@erogray  yes If the dataset already has an accrualPeriodicity value we will not overwrite it, if the dataset is trying to give two varying values for the frequency with which dataset is published I don't think that is on us to support the inconsistency.

**Comment by dafeder** [comment]
The POD standard allows for different values in both of the fields and in fact there are situations where that would make sense. The data could be granular to the minute but only _updated_ daily, for instance. If this fix allows a particular harvest we're struggling with to complete I think it's OK as a temporary solution, but my thought is we should actually change the source_updated field to be a plain text field and use PHP to validate for all the permutations of ISO 8601 that the Project Open Data spec allows.

**Comment by janette** [comment]
@dafeder the field in question is the modified date field, are you saying we should add a **new** field (source_updated) to hold the ISO key value if one is provided via the 'modified date'

**Comment by dafeder** [comment]
@janette sorry, I meant field_harvest_source_modified. That's where the updated field from the harvest should be getting stored. I'm saying replace that field with a plain text (not feasible for this upcoming release but maybe 1.16).

**Comment by janette** [comment]
@dafeder Ah that makes sense, thanks.

**Comment by janette** [comment]
this belongs on the develop branch so closing in favor of #2627

**Pull request closed without merging**
