### PR TITLE
Form widget based on JSON Schema

### LINKED ISSUE #3166: Move from rjsf to Drupal Form API
## Description
The idea is to move away from react-jsonschema-form and create the dataset form based on a JSON schema using the Drupal Form API so we can have full control over the form and still have all the drupal capabilities available.

## Requirements
- Map basic fields from the JSON schema to form API widgets (this should include validators for the fields)
- Build the metadata based on submitted values and create the dataset (and references).
- Get as many fields working as possible and create extra tickets for the ones that does not.
- Support UI schema based on rjsf UI schema.
- Support adding objects like distributions as needed.

## Acceptance Criteria
- A form is created based on the current DKAN JSON Schema and a schema-ui.
- The form is available in a demo page.

### PR DESCRIPTION
**Pull request by dharizza**
## Test steps
- [x] Enable the json_form_widget module.
- [x] Go to Structure -> Content types -> Data -> Manage form display, select the widget "JSON Form" for the field "JSON Metadata", make the schema be "dataset" and save the configuration.
- [x] Create a new data node, the form should load correctly with fields for the different elements from the schema defined. Once you add values and save, a new dataset should be created correctly with JSON saved in the node (check the node page to confirm).
- [x] Edit an existing dataset, the form should load correctly with all the information from the node, you should be able to edit some values and save the form without errors. 
- Confirm the following is true on the forms:
  - [ ] If the schema configured for the field does not exist, then the form is not shown.
  - [ ] If the schema UI does not exist, then the form is still shown based just in the JSON Schema.
  - [x] You can add multiple Categories and Tags to a node.
  - [x] You can add multiple distributions to a dataset.
  - [x] You can add multiple fields to the "Schema" of a distribution.
- The schema UI should be applied correctly, check:
  - [x] You can make fields to be hidden by adding:
```
"@type": {
    "ui:options": {
      "widget": "hidden"
    }
  },
```

  - [x] You can change the widget of a field to be a textarea and configure the amount of rows and cols displayed by adding:
```
"spatial": {
    "ui:options": {
      "widget": "textarea",
      "rows": 5,
      "cols": 60,
    }
  },
```

  - [x] You can disable a field by adding:
```
"accessLevel": {
    "ui:options": {
      "disabled": true
    }
  },
```

  - [x] You can add a placeholder to fields by adding:
```
"modified": {
    "ui:options": {
      "placeholder": "YYYY-MM-DD"
    }
  },
```

  - [x] You can override the field description/help text by adding:
```
"field_name": {
    "ui:options": {
      "description": "Test help text.",
    }
  },
```

  - [x] You can override the field title by adding:
```
"description": {
    "ui:options": {
      "title": "More descriptive title"
    }
  },
```
  - [x] You can use the dkan_uuid widget in a field to pre-fill it with a valid UUID and make it invisible:
```
"identifier": {	
    "ui:options": {	
      "widget": "dkan_uuid"	
    }	
  },
```
  - [x] You can override array fields and its subfields:
```
"references": {
    "ui:options": {
      "title": "Better title.",
    },
    "items": {
      "ui:options": {
        "placeholder": "http://"
      }
    }
  },
```
  - [x] You can override object fields and its subfields:
```
"publisher": {
    "ui:options": {
      "description": "Better description.",
    },
    "properties": {
      "@type": {
        "ui:options": {
          "widget": "hidden"
        }
      }
    }
  },
```

### CODE REVIEW

**Comment by grugnog** [comment]
Can one of the admins verify this patch?

**Comment by janette** [comment]
Thoughts:
- let's add the dkan_uuid widget by default
- why is the distribution title required?
- error message `The property keyword is required` could be confusing as the field is labeled 'Tags'
- also may not be clear `Does not match the regex pattern ^mailto:[\w\_\~\!\$\&\'\(\)\*\+\,\;\=\:.-]+@[\w.-]+\.[\w.-]+?$|[\w\_\~\!\$\&\'\(\)\*\+\,\;\=\:.-]+@[\w.-]+\.[\w.-]+?$ `
- we should add some style overrides to make the nested fieldsets less awkward and some js on validation to take the user to the specific field that needs attention.
- the keyword and email fields display errors in a very different way than the other required fields
- typo: change wether -> whether

**Comment by dharizza** [comment]
Fixed typo and merge conflicts. The rest of the comments will be addressed in the following tickets:
- https://github.com/GetDKAN/dkan/issues/3314
- https://github.com/GetDKAN/dkan/issues/3313
- https://github.com/GetDKAN/dkan/issues/3312
- https://github.com/GetDKAN/dkan/issues/3311

**Comment by janette** [comment]
@Dharizza when creating a dataset without any distribution info, it still generates a new data node with just the identifier. How hard would it be to add a check for any distribution values before generating a distribution node?

Also, I don't see anything on the board about the other property schemas (keyword, theme, publisher, dist) what is the short term work around until the entity refactor is complete?

**Pull request merged**
