### PR TITLE
Make DKAN work without decoupled frontend

### LINKED ISSUE #3249: Dataset page for Drupal themes
* Twig template for Dataset nodes using Drupal naming conventions in metastore module
* As much as the JSON blob rendered in this template (title, description, resources, org, metadata table)
* Library for rendering data table lives in datastore module
* Page always loads data table library (or maybe use conditional)

### PR DESCRIPTION
**Pull request by dafeder**
fixes [org/repo/issue#]

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

### CODE REVIEW

**Comment by dafeder** [comment]
WIP is an understatement, but we have some experimental theme functions that give us some basics in a normal Drupal theme:

image

**Comment by grugnog** [comment]
Can one of the admins verify this patch?

**Comment by dafeder** [comment]
We should come back to this!

**Review by janette — APPROVED** [review]

**Comment by janette** [comment]
work was moved to #3914 and merged

**Pull request closed without merging**
