### PR TITLE
Replace CircleCI scripting with custom docker image.

### PR DESCRIPTION
**Pull request by Pythagory**
Experimental feature enhancement - Builds on work done in #2237 by moving some of the customization of the CircleCI php image to a custom docker image. In theory, this should simplify the process of using this image with Ahoy for local development, while also speeding up the build/test process.

### CODE REVIEW

**Comment by Pythagory** [comment]
Still TODO: Create GetDKAN org on docker hub, move docker images there, update this PR to reference those images.

**Comment by Pythagory** [comment]
Transferred dockerfile repository to GetDKAN: https://github.com/GetDKAN/dkan-docker
Created GetDKAN org on docker hub, recreated repository: https://hub.docker.com/r/getdkan/dkan-docker/

**Comment by fmizzell** [comment]
@Pythagory Is the plan to change our local images to use the CircleCI based images?

**Comment by kimwdavidson** [comment]
Done.

**Pull request closed without merging**
