### PR TITLE
Prevent fatal error when processing dataset resources.

### LINKED ISSUE #3572: Encountering fatal error whenever running the `resource_purger` queue.
## Describe the bug

Whenever I attempt to run the `resource_purger` queue, I receive the following error:
```
TypeError: Argument 1 passed to Drupal\datastore\Service\ResourcePurger::delete() must be of the type string, null given, called in /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php on line 195 in Drupal\datastore\Service\ResourcePurger->delete() (line 319 of /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php) #0 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(195): Drupal\datastore\Service\ResourcePurger->delete(NULL, NULL)
#1 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(167): Drupal\datastore\Service\ResourcePurger->purge(31441, '63ce305b-b934-4...', false)
#2 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(150): Drupal\datastore\Service\ResourcePurger->purgeHelper(31441, '63ce305b-b934-4...', false)
#3 /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Plugin/QueueWorker/ResourcePurgerWorker.php(52): Drupal\datastore\Service\ResourcePurger->purgeMultiple(Array, false)
#4 /mnt/www/html/datahealthcarestg/docroot/core/lib/Drupal/Core/Cron.php(180): Drupal\datastore\Plugin\QueueWorker\ResourcePurgerWorker->processItem(Array)
#5 /mnt/www/html/datahealthcarestg/docroot/core/lib/Drupal/Core/Cron.php(145): Drupal\Core\Cron->processQueues()
#6 /mnt/www/html/datahealthcarestg/docroot/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#7 /mnt/www/html/datahealthcarestg/vendor/drush/drush/src/Drupal/Commands/core/DrupalCommands.php(76): Drupal\Core\ProxyClass\Cron->run()
#8 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron(Array)
#9 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#10 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /mnt/www/html/datahealthcarestg/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /mnt/www/html/datahealthcarestg/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /mnt/www/html/datahealthcarestg/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /mnt/www/html/datahealthcarestg/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /mnt/www/html/datahealthcarestg/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#20 /mnt/www/html/datahealthcarestg/vendor/drush/drush/drush(4): require('/mnt/www/html/d...')
#21 {main}. 
TypeError: Argument 1 passed to Drupal\datastore\Service\ResourcePurger::delete() must be of the type string, null given, called in /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php on line 195 in Drupal\datastore\Service\ResourcePurger->delete() (line 319 of /mnt/www/html/datahealthcarestg/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php).
```

This wouldn't be such a big deal if it wasn't for:
1. The queue item responsible for creating the above error appears to be re-queued on error.
2. If the queue items are processed using the `drush cron` command, the above error is fatal, and all subsequent queue items are never processed.

## Steps To Reproduce

1. Navigate to the Dataset Creation page (`/node/add/data`).
2. Fill out all of the required fields.
3. Fill out the distribution title field and the distribution format field, but not the Download URL field.
4. Save the dataset.
5. Edit the newly created dataset.
6. Provide a resource for the Download URL field.
7. Save the dataset.
8. Run the `resource_purger` queue.
9. Verify that you encountered the above error.

## Expected behavior

Running the `resource_purger` queue should not result in the above error.

### PR DESCRIPTION
**Pull request by clayliddell**
fixes #3572 

## QA Steps

1. Navigate to the Dataset Creation page (`/node/add/data`).
2. Fill out all of the required fields.
3. Fill out the distribution title field and the distribution format field, but not the Download URL field.
4. Save the dataset.
5. Edit the newly created dataset.
6. Provide a resource for the Download URL field.
7. Save the dataset.
8. Run the `resource_purger` queue.
9. Ensure you do not encounter either of the following errors:
```
TypeError: Argument 1 passed to Drupal\datastore\Service\ResourcePurger::delete() must be of the type string, null given, called in /var/www/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php on line 195 in Drupal\datastore\Service\ResourcePurger->delete() (line 319 of /var/www/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php) #0 /var/www/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(195): Drupal\datastore\Service\ResourcePurger->delete(NULL, NULL)
#1 /var/www/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(167): Drupal\datastore\Service\ResourcePurger->purge(60, '5afbe096-37d6-4...', false)
#2 /var/www/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourcePurger.php(150): Drupal\datastore\Service\ResourcePurger->purgeHelper(60, '5afbe096-37d6-4...', false)
#3 /var/www/docroot/modules/contrib/dkan/modules/datastore/src/Plugin/QueueWorker/ResourcePurgerWorker.php(52): Drupal\datastore\Service\ResourcePurger->purgeMultiple(Array, false)
#4 /var/www/vendor/drush/drush/src/Drupal/Commands/core/QueueCommands.php(77): Drupal\datastore\Plugin\QueueWorker\ResourcePurgerWorker->processItem(Array)
#5 [internal function]: Drush\Drupal\Commands\core\QueueCommands->run('resource_purger', Array)
#6 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#7 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#8 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#9 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#17 /var/www/vendor/drush/drush/drush(4): require('/var/www/vendor...')
#18 {main}.
```
```
TypeError: Argument 1 passed to Drupal\metastore\ResourceMapper::get() must be of the type string, null given, called in /var/www/docroot/modules/contrib/dkan/modules/metastore/src/EventSubscriber/MetastoreSubscriber.php on line 81 in /var/www/docroot/modules/contrib/dkan/modules/metastore/src/ResourceMapper.php on line 112 #0 /var/www/docroot/modules/contrib/dkan/modules/metastore/src/EventSubscriber/MetastoreSubscriber.php(81): Drupal\metastore\ResourceMapper->get(NULL, NULL, NULL)
#1 [internal function]: Drupal\metastore\EventSubscriber\MetastoreSubscriber->cleanResourceMapperTable(Object(Drupal\common\Events\Event), 'metastore_orpha...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /var/www/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\common\Events\Event), 'metastore_orpha...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#3 /var/www/docroot/modules/contrib/dkan/modules/common/src/EventDispatcherTrait.php(36): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('metastore_orpha...', Object(Drupal\common\Events\Event))
#4 /var/www/docroot/modules/contrib/dkan/modules/metastore/src/Plugin/QueueWorker/OrphanReferenceProcessor.php(126): Drupal\metastore\Plugin\QueueWorker\OrphanReferenceProcessor->dispatchEvent('metastore_orpha...', '882887c5-aee8-5...')
#5 /var/www/docroot/modules/contrib/dkan/modules/metastore/src/Plugin/QueueWorker/OrphanReferenceProcessor.php(104): Drupal\metastore\Plugin\QueueWorker\OrphanReferenceProcessor->unpublishReference('distribution', '882887c5-aee8-5...')
#6 /var/www/docroot/core/lib/Drupal/Core/Cron.php(180): Drupal\metastore\Plugin\QueueWorker\OrphanReferenceProcessor->processItem(Object(Drupal\metastore\NodeWrapper\Data))
#7 /var/www/docroot/core/lib/Drupal/Core/Cron.php(145): Drupal\Core\Cron->processQueues()
#8 /var/www/docroot/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#9 /var/www/vendor/drush/drush/src/Drupal/Commands/core/DrupalCommands.php(76): Drupal\Core\ProxyClass\Cron->run()
#10 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron(Array)
#11 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#12 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#15 /var/www/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#22 /var/www/vendor/drush/drush/drush(4): require('/var/www/vendor...')
#23 {main}
TypeError: Argument 1 passed to Drupal\metastore\ResourceMapper::get() must be of the type string, null given, called in /var/www/docroot/modules/contrib/dkan/modules/metastore/src/EventSubscriber/MetastoreSubscriber.php on line 81 in Drupal\metastore\ResourceMapper->get() (line 112 of /var/www/docroot/modules/contrib/dkan/modules/metastore/src/ResourceMapper.php).
```

### CODE REVIEW

**Comment by clayliddell** [comment]
This "expected value for optional resource" error occurs in more places than here. I'm still assessing the areas of DKAN affected by this bug.

**Comment by grugnog** [comment]
This looks good to me, but I don't know enough about DKAN internals to know if there are possible side effects to consider.
@clayliddel - the codeclimate check may need looking at, also I wonder if we need a test for the exception?

**Comment by clayliddell** [comment]
@grugnog I'm not terribly familiar with how testing is handled in DKAN, so I might need some help on that :sweat_smile:.
@dafeder I think I have an idea for how to satisfy CodeClimate, but I don't want to push to the branch if your still working on it.

**Comment by dafeder** [comment]
@clayliddell to fix codeclimate issue

**Pull request merged**
