### PR TITLE
Dataset/harvest dashboard separation

### LINKED ISSUE #3538: Dataset dasboard separate from harvest dashboard
We have some very useful interfaces in the harvest_dashboard module, but the importer status stuff is not available for datasets outside of harvests.

To improve visibility of import status let's:

1. Separate the Harvest Dashboard main page and the Harvest-specific page into two sepratate menu items. We will have a new page called "Datastore Import Status", with filters including "harvest." Move the Code for this page into the datastore module.
2. Fix the links in the harvest dashboard and make sure they go to the right place. Move the harvest dashboard code into the main harvest module and start phasing out the harvest_dashboard module.
3. We should make this information easier to find via the API, in a way that more closely resembles the dashboard. Propose and addition to or modification of the datastore API in another ticket.

### PR DESCRIPTION
**Pull request by klimp-drupal**
fixes [GetDKAN/dkan/issues/3538]

- [ ] harvest_dashboard module deleted
- [ ] the code from `harvest_dashboard` is moved to the datastore and `harvest` modules

## QA Steps

- [ ] create a harvest
```bash
drush dkan:harvest:register '{"identifier":"h1","extract":{"type":"\\Harvest\\ETL\\Extract\\DataJson","uri":"https://dkan-default-content-files.s3.amazonaws.com/data.json"},"transforms":[],"load":{"type":"\\Drupal\\harvest\\Load\\Dataset"}}'
```
- [ ] run it `drush dkan:harvest:run h1`
- [ ] access `/admin/dkan/harvest_dashboard` and see your harvest created
- [ ] click on the harvest name to get to the harvest specific page `/admin/dkan/dataset-status/h1`
- [ ] create a dataset not from harvest (via UI or API call)
- [ ] access `/admin/dkan/dataset-status` the page with all datasets listed (harvested + non harvested)
- [ ] create a dataset without a distribution, or distribution without a resource - make sure they are listed on the dashboard and cause no errors

### CODE REVIEW

**Comment by dafeder** [comment]
@klimp-drupal I think something must have been unclear in the original ticket. When we load the dataset/datastore dashboard, we should see _all_ datasets and their datastore status. Visiting the QA site which has several datasets in the datastore but no harvests, I don't see anything in the datastore status page.

**Comment by klimp-drupal** [comment]
> When we load the dataset/datastore dashboard, we should see _all_ datasets and their datastore status.

Will do

**Comment by klimp-drupal** [comment]
Fixed the dashboard to load all the datasets, not only harvested

**Comment by klimp-drupal** [comment]
Added pagination

**Comment by klimp-drupal** [comment]
Datasets with no distributions and distributions without resources don't cause issues on the dashboard any more

**Comment by janette** [comment]
@klimp-drupal  @dafeder 

Let's stop using underscores in our paths.
Can `/admin/dkan/datasets_import_status_dashboard/{harvestId}` just be `/admin/dkan/dataset-status/{harvestId}`?

(scope creep alert) and change:
`/admin/dkan/harvest_dashboard` to -> `admin/dkan/harvest`
`/admin/dkan/sql_endpoint` to -> `admin/dkan/sql-endpoint`

**Comment by dafeder** [comment]
This would break on update on sites that already have harvest_dashboard installed. Re-added just the yml file and added update hook to uninstall.

**Review by clayliddell — APPROVED** [review]
Looks good to me!

**Review by dafeder — APPROVED** [review]

**Pull request merged**
