### PR TITLE
Creating OpenDataStandards.md

### LINKED ISSUE #2199: Document Open Data Standards and Best Practices
Stefanie  has this in Google Doc format. Needs to be converted to markdown and added to Read the Docs.

### PR DESCRIPTION
**Pull request by stefaniefgray**
Necessary documentation; see https://github.com/GetDKAN/dkan/issues/2199

Fixes #2199

### CODE REVIEW

**Comment by janette** [comment]
@stefaniefgray can you use rst rather than md

**Comment by janette** [comment]
@stefaniefgray do you have the images for this document?

**Comment by stefaniefgray** [comment]
@janette Here they are! There should just be these 3: https://github.com/GetDKAN/dkan/pull/2210/commits/82fd8e2fb42746a4fc9b1d20c453b35f77153e42

**Comment by janette** [comment]
@stefaniefgray Thanks, one last question, do the Open Data Experts know their contact info will be in the docs?

**Comment by stefaniefgray** [comment]
@janette Err -- perhaps we should remove that section for now and direct people toward DKAN community resources

**Pull request merged**
