### PR TITLE
Allow LOAD DATA LOCAL INFILE option

### LINKED ISSUE #3473: Refactor the datastore importer to allow a LOAD DATA LOCAL INFILE option
## Due date:
June 2nd

## User Story: 
- I should be able to add a dataset with a 7GB resource and have it complete importing under ~10 min.
- When I turn on a new module for this, the load data importer will be the system-wide importer used. There is no additional configuration after enabling to start using it.

## Description: 
To make the data import of 8GB files more efficient, we need a second import method for servers that allow LOAD DATA LOCAL INFILE.
This will cut down a 10 hour import to 9 minutes.

## Estimate: 
5

### PR DESCRIPTION
**Pull request by dharizza**
fixes #3473 

## QA Steps

- [ ] Enable the module datastore_fast_import
- [ ] Add a distribution with a file bigger than 5GB, for example you could do it with harvest following these steps:
  - [ ] Create the file harvest.json in sites/default/files with this content:
```
{
  "@context": "https:\/\/project-open-data.cio.gov\/v1.1\/schema\/catalog.jsonld",
  "@id": "http:\/\/fake.com\/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https:\/\/project-open-data.cio.gov\/v1.1\/schema",
  "describedBy": "https:\/\/project-open-data.cio.gov\/v1.1\/schema\/catalog.json",
  "dataset": [
    {
      "@type": "dcat:Dataset",
      "accessLevel": "public",
      "contactPoint": {
        "fn": "admin",
        "hasEmail": "mailto:noemailprovided@usa.gov"
      },
      "description": "Test description",
      "distribution": [
        {
          "@type": "dcat:Distribution",
          "downloadURL": "https:\/\/wecms-op.s3.us-east-2.amazonaws.com\/OP_DTL_GNRL_PGYR2015_P01222021.csv",
          "mediaType": "text\/csv",
          "format": "csv",
          "title": "Test Resource"
        }
      ],
      "identifier": "333cd327-4e5d-43f9-8eb1-c11850fa7c88",
      "issued": "2016-06-22",
      "modified": "2019-08-12",
      "publisher": {
        "@type": "org:Organization",
        "name": "demo.getdkan.com"
      },
      "theme": [
        "Test"
      ],
      "title": "Test Dataset",
      "keyword": [
        "No keyword provided"
      ]
    }
  ]
}
```
  - [ ] Run `dktl drush dkan:harvest:register '{"identifier":"plan","extract":{"type":"\\Harvest\\ETL\\Extract\\DataJson","uri":"http://dkan.localtest.me/sites/default/files/harvest.json"},"transforms":[],"load":{"type":"\\Drupal\\harvest\\Load\\Dataset"}}'`
  - [ ] Run `dktl drush dkan:harvest:run plan`
  - [ ] Run `dktl drush queue:run datastore_import`
- [ ] The import should finish correctly in less than 30mins

### CODE REVIEW

**Comment by janette** [comment]
On existing db:
After `updb -y`
running `cim -y` results in:

```
Error: Call to a member function setSyncing() on null in Drupal\Core\Config\Entity\ConfigEntityStorage->importDelete() (line 389 of /mnt/www/html/openpaymentsstg/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php) #0 /mnt/www/html/openpaymentsstg/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(997): Drupal\Core\Config\Entity\ConfigEntityStorage->importDelete('views.view.cont...', Object(Drupal\Core\Config\Config), Object(Drupal\Core\Config\Config))
```
user-page-after-log-in

Created a dataset via the UI, got a success message but in the logs

log-message

**Comment by janette** [comment]
**Testing report:** column names larger than 64 characters: e.g.  _Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value_

Column not found: 1054 Unknown column 'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value' in 'field list'

```
| d7fb2059d7a1af2cc3039e2d83ff0c6f | {"parser":{"@type":"object","@class":"CsvParser\\Parser\\Csv","data":{"delimiter":",","quote":"\"","escape":"^","recordEnd":["\n","\r"],"records":[],"fields":[],"field":"","machine":{"currentStates":["s_new_field"],"halted":false,"machines":[]}}},"identifier":"d7fb2059d7a1af2cc3039e2d83ff0c6f","result":{"@type":"object","@class":"Procrastinator\\Result","data":{"status":"error","data":"","error":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value' in 'field list': LOAD DATA LOCAL INFILE '\/mnt\/gfs\/env\/sites\/default\/files\/resources\/fddfc9cb48bfe27df72f3e514ccf8e44_1625096249\/myfile.csv' INTO TABLE datastore_d7fb2059d7a1af2cc3039e2d83ff0c6f FIELDS TERMINATED BY ',' ENCLOSED BY '\\\"' LINES TERMINATED BY '\\n' IGNORE 1 ROWS (Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,Recipient_Zip_Code,Recipient_Country,Recipient_Province,Recipient_Postal_Code,Physician_Primary_Type,Physician_Specialty,Physician_License_State_code1,Physician_License_State_code2,Physician_License_State_code3,Physician_License_State_code4,Physician_License_State_code5,Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country,Total_Amount_of_Payment_USDollars,Date_of_Payment,Number_of_Payments_Included_in_Total_Amount,Form_of_Payment_or_Transfer_of_Value,Nature_of_Payment_or_Transfer_of_Value,City_of_Travel,State_of_Travel,Country_of_Travel,Physician_Ownership_Indicator,Third_Party_Payment_Recipient_Indicator,Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value,Charity_Indicator,Third_Party_Equals_Covered_Recipient_Indicator,Contextual_Information,Delay_in_Publication_Indicator,Record_ID,Dispute_Status_for_Publication,Related_Product_Indicator,Covered_or_Noncovered_Indicator_1,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1,Product_Category_or_Therapeutic_Area_1,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1,Associated_Drug_or_Biological_NDC_1,Covered_or_Noncovered_Indicator_2,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2,Product_Category_or_Therapeutic_Area_2,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2,Associated_Drug_or_Biological_NDC_2,Covered_or_Noncovered_Indicator_3,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3,Product_Category_or_Therapeutic_Area_3,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3,Associated_Drug_or_Biological_NDC_3,Covered_or_Noncovered_Indicator_4,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4,Product_Category_or_Therapeutic_Area_4,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4,Associated_Drug_or_Biological_NDC_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Program_Year,Payment_Publication_Date) SET record_number = NULL; Array\n(\n)\n"}},"timeLimit":50}
```

**Comment by susisiman** [comment]
@janette tested this - duplicate rows have been fixed. @dafeder is currently reviewing this ticket and making the necessary changes.

**Comment by dafeder** [comment]
Doing a slight refactor, adding a factory for the mysql import and using services to override the main importer when module is enabled, to avoid having to inject the module handler and use conditional logic.

**Comment by dafeder** [comment]
Merging despite poor diff coverage -- experimental module not covered by code coverage metrics.

**Pull request merged**
