### PR TITLE
DKAN Data Dictionaries and Validation (7.x-1.x rebase post 1.6 release)

### PR DESCRIPTION
**Pull request by rhabbachi**
**Main Epic**:
Connects #2608

**Implementation Tickets**:
Connects #2674
Connects #2675
Connects #2676 
Connects #2677 
Connects #2678 
Connects #2679 
Connects #2680

### CODE REVIEW

**Comment by rhabbachi** [comment]
Status at this point of the code:

* #2674 is almost there, data dictionaries implementations are discoverable via the drupal hook system. No mock implementation yet as the interfaces are still WIP.
* #2675 Tableschema Data Dictionary with Validation is available. As well as a plain CSV Data Dictionary (without validation).
* #2676,  #2678  Initial version of the "Validation" tab is available and users can trigger validation events. Still need to make sure validation permissions are assigned to the Editor role.
*  #2677 not yet implemented.
*  #2679 not yet implemented.
* #2680 No proper documentation yet.

**Comment by acouch** [comment]
YES!!!!

cries in 76ers

**Comment by janette** [comment]
@rhabbachi could you rebase 😄 there's been some "small" changes since you've submitted this

**Comment by rhabbachi** [comment]
@janette yeah clearly :smile: Will try to rebase (and maybe cleanup) this week.

**Comment by susisiman** [comment]
Closing due to inactivity. Please feel free to open!

**Pull request closed without merging**
