### PR TITLE
Updating Add Content page and content types

### PR DESCRIPTION
**Pull request by stefaniefgray**
Cut out very wordy language; unnecessary "sales" type jargon.

Description. Please write any background information about this PR you think is useful for the product team. Use any of the items below that are relevant to this pull request, and delete any that are not.

## User story

If this PR introduces new functionality, include a user story or stories describing what this pull request is intended for.

## How to reproduce

1.  If the PR fixes a bug, include step-by-step instructions for reproducing the bug on a current DKAN release.

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

## Merge process

- [ ] Note if there is a special sequence for merging (such as PRs on other repos that need to be merged first) or other abnormalities to look out for.

## Reminders

- [ ] There is test for the issue.
- [ ] CHANGELOG updated.
- [ ] Coding standards checked.
- [ ] Review docs.getdkan.com (or in /docs) to see if it still covers the scope of the PR and update if needed.

### CODE REVIEW

**Comment by erogray** [comment]
Looks good from here.

**Comment by erogray** [comment]
@janette can this be merged?

**Comment by janette** [comment]
@erogray @stefaniefgray 
No, the markup is really wonky, node type descriptions are in quote format, subheads are larger that headings, needs work.

**Comment by erogray** [comment]
Adding for my own future reference, since I didn't look before: https://docs.getdkan.com/en/latest/admin/data_and_content/adding_new_content.html

**Pull request merged**
