### PR TITLE
Update the dkan admin view to filter by dataset by default

### PR DESCRIPTION
**Pull request by janette**
The title of the dkan content view, is 'Datasets' so let's default to show just the datasets by default

## QA Steps

- [ ] Navigate to `/admin/dkan/datasets` and confirm you only see datasets by default and can use the UI to select other options

### CODE REVIEW

**Comment by susisiman** [comment]
@dafeder is working on this ticket. Not a high priority but if there is time he will work on it.  @janette did we test this on an upgrade?

**Comment by dafeder** [comment]
Assigning to @janette to confirm upgrade behavior.

**Comment by dafeder** [comment]
Blocked for now by #3556

**Comment by dafeder** [comment]
Glad we finally got those upgrade tests working!

**Pull request merged**
