### PR TITLE
Civic-2251 composer path fix and drush version update to 8.0.5 for Circle CI

### PR DESCRIPTION
**Pull request by asghaier**
CircleCI tests break and does not build properly for multiple Dkan related repositories. This requires fixing composer path.
Also Drush version is outdated (8.0.2) and needs to be updated to the latest which is 8.0.5

### CODE REVIEW

**Comment by asghaier** [comment]
DO NOT MERGE YET, This did not fix the issue.

**Comment by asghaier** [comment]
This PR is stable and safe to merge.
Please test and merge.

**Comment by asghaier** [comment]
DO NOT MERGE, no longer required for related repositories (site repositories and module repositories) to run Circle CI tests and build Probo CI test sites.

**Comment by asghaier** [comment]
This should be safe to merge.
This specifically fixes upgrading Drush version to a newer version.
It removes the composer folder in the home directory .composer and .config/composer to make sure all Drush dependencies gets pulled and are fresh (This way we can avoid having complex dependencies conflicts)

**Comment by dkinzer** [comment]
@asghaier the circle CI for this PR are failing (not for timeout but actually failing)  So I'm holding off on merging this... I've restarted the build.

**Comment by asghaier** [comment]
Just rebased this and upgraded Drush from 8.1.0 to 8.1.3
It will be ready to be merged into Dkan once the probo and circle tests are done @acouch

**Comment by dkinzer** [comment]
@asghaier tests are still failing on this branch... I'm rebasing in case it helps.

**Comment by kimwdavidson** [comment]
No longer relevant. Closing.

**Pull request closed without merging**
