### PR TITLE
Dataset collections et

### PR DESCRIPTION
**Pull request by ethanteague**
Connects https://github.com/isdapps/adc-code/issues/1674
Connects https://github.com/isdapps/adc-code/issues/1679
Connects https://github.com/isdapps/adc-code/issues/1680
Connects https://github.com/isdapps/adc-code/issues/1681
Connects https://github.com/isdapps/adc-code/issues/1682

## QA
[ ] Add a dataset to a parent via the collection field on the node form
[ ] After saving node, confirm collection link to parent appears in the metadata table
[ ] Visit the parent, and confirm the collection header reads "In this Collection"
[ ] Confirm there is a see all link
[ ] Confirm there is a total number of results displayed
[ ] Confirm body (description) field of parent is above collections block (you may need to edit dataset to add text).
[ ] Visit the search page, and confirm the Collection facet reads "Collection"
[ ] Confirm Collection facet is closed (by default)
[ ] Up to reviewer: task called for researching limit in facet to prevent user from getting overwhelmed with dozens of collections. Facets by default has a max limit of 20, but I set it to 15. If you want to populate multiple parents to test, cool, but I think we are safe.h
[ ] Add a new dataset.
[ ] Confirm collections field appears on the Additional data page underneath author field.
[ ] Confirm there is help text link underneath the collections field.
[ ] Edit an existing dataset, and add a node to the collection field.
[ ] Edit another existing dataset, that is not the parent item you added to the previous dataset, and verify that the previous dataset is not available in the collections autocomplete field.

### CODE REVIEW

**Comment by JayDarnell** [comment]
Code review looks good

**Comment by kimwdavidson** [comment]
## QA
[x] Add a dataset to a parent via the collection field on the node form
**QA PASS** (Sort of - the autofill suggestion is a link, so if I click on the name, it takes me to that dataset. If I click off the name in a blank space next to the name, it autofills)
[x] After saving node, confirm collection link to parent appears in the metadata table
**QA PASS**
[x] Visit the parent, and confirm the collection header reads "In this Collection"
**QA PASS**
[x] Confirm there is a see all link
**QA PASS**
[x] Confirm there is a total number of results displayed
**QA PASS** But it's in a kind of unintuitive location. Might be better as "See all (#)"?
[x] Confirm body (description) field of parent is above collections block (you may need to edit dataset to add text).
**QA PASS**
[x] Visit the search page, and confirm the Collection facet reads "Collection"
**QA PASS*
[ ] Confirm Collection facet is closed (by default)
**QA FAIL** Collection facet is open when I click on the "See all" link
[ ] Up to reviewer: task called for researching limit in facet to prevent user from getting overwhelmed with dozens of collections. Facets by default has a max limit of 20, but I set it to 15. If you want to populate multiple parents to test, cool, but I think we are safe.h
[x] Add a new dataset.
[x] Confirm collections field appears on the Additional data page underneath author field.
**QA PASS**
[x] Confirm there is help text link underneath the collections field.
**QA PASS** But maybe there's more helpful text? "Collections allow you to group datasets together. See more" with a link?
[x] Edit an existing dataset, and add a node to the collection field.
[x] Edit another existing dataset, that is not the parent item you added to the previous dataset, and verify that the previous dataset is not available in the collections autocomplete field.
**QA PASS**

**Comment by dafeder** [comment]
Still failing tests @ethanteague

**Comment by ethanteague** [comment]
Failure was occurring because test was looking for collections field on first step, but we've moved to 3rd step of form since writing this test, @dafeder. Fix is now in place.

**Comment by dafeder** [comment]
Had to switch this to the collections branch, since this isn't merging into develop quite yet.

**Pull request merged**
