### PR TITLE
Pause Import

### PR DESCRIPTION
**Pull request by fmizzell**
Connects #2684
**QA**
- Create a resource with a large file, like https://data.ca.gov/sites/default/files/SafeToSwim_2018-09-04.csv
- Start a datastore import from the UI
- Run cron from drush
- Go back to the UI, you should see that the datastore is in progress and a stop button should be available
- Press the stop button
- A message will let you know that the import will be stopped soon
- Refres the page
- The status should now be paused

### CODE REVIEW

**Comment by dafeder** [comment]
## QA Report

After trying to add that file as a remote resource, I got this:

image

Uploading it worked without issue and I was able to start an import. We still have the issue where the message we see after the batch is "import finished" when in fact it is not complete. Still, I was able to run cron and re-start the import. 

"Stop" works.

What I'm concerned about (and I think we've discussed this before) is that when you're in that paused state, it's very unclear where to go from there. The only button available is "Drop." It seems like we should have some sort of message to the user explaining that importing has been paused, and will resume on the next cron run. 

I also wonder if we might want to make an import button available in the paused state, where it would let you at least move a bit further ahead again.

**Comment by dafeder** [comment]
Another interesting note: after letting cron run for a long time the second time, it stalled eventually and displayed this:

image

When I run cron again, it completes immediately and does not import any further items. At this point, the datastore is still in an "In Progress" state. Pressing the "Stop" button does not seem to have an effect.

**Comment by dafeder** [comment]
I can no longer import any other resource once the site gets into the state described above ^^^

**Comment by dafeder** [comment]
Back to the remote file issue: the resource works as expected despite warnings after creation. I can import a file to the datastore, resume on cron, and use the stop button. The cron will "time out" in the same manner as with the local file as described above, and leave the site in the same broken state.

**Comment by fmizzell** [comment]
@dafeder I just pushed some code to restrict the datastore from running during UI cron calls. The datastore imports are meant to be long running processes, so they don't make sense to run from the UI. I also changed the message given when batch completes to be less deceiving.

**Pull request merged**
