### PR TITLE
Update contrib modules

### PR DESCRIPTION
**Pull request by janette**
- diff 3.4
- features 2.11
- file_entity 2.22
- honeypot 1.25
- libraries 2.5
- migrate 2.11
- panopoly_images 1.57
- search_api 1.25

### CODE REVIEW

**Comment by dafeder** [comment]
Blocked until we fix tests, that work happening in #2646

**Comment by janette** [comment]
looks like the harvest tear down in @afterScenario  is broken

**Comment by dafeder** [comment]
Trying this without Migrate to see if tests pass.

**Comment by janette** [comment]
closing in favor of https://github.com/GetDKAN/dkan/pull/2788

**Pull request closed without merging**
