### PR TITLE
Allow deleting a harvest without deleting its datasets

### PR DESCRIPTION
**Pull request by thierrydallacroce**
Proposed fix for [#3839]

### Steps to test

1. Create and run a harvest
2. Verify the harvest is registered, i.e. shown in the output of `drush dkan:harvest:list`
3. Verify its datasets exist and are published
4. Deregister the harvest: `drush dkan:harvest:deregister HARVEST_ID  --revert`
5. Verify the harvest is no longer shown in the output of `drush dkan:harvest:list`
6. Verify its datasets still exist, and are published

### CODE REVIEW

**Comment by thierrydallacroce** [comment]
@dafeder, I re-tested this locally to be sure, spinning up both of my environments from scratch with their minimal content.

In one of them, `drush dkan:harvest:deregister test_minimal__data` removed the harvest but kept the datasets, while in the other `drush dkan:harvest:deregister test_minimal__data --revert` removed both the harvest and its datasets.

**Review by dafeder — DISMISSED** [review]

**Comment by thierrydallacroce** [comment]
@dafeder made me aware of a use case which invalidates this approach and PR.

**Comment by stefan-korn** [comment]
@dafeder @thierrydallacroce : Could you explain why there is a use case which invalidates this approach and PR?

Is there actually a possibility to delete a harvest without deleting its datasets?

**Comment by dafeder** [comment]
@stefan-korn uf, it's been a while and I wish we'd documented the details of this discussion in the thread! My memory here is that the PR went a little too far and removed the revert command, making revert only possible as part of a deregister. There are legitimate use-cases for both deregistering w/o revert, and reverting w/o deregister. I think we were going to just redo this to remove the revert piece from deregister completely, and add a warning if you deregister a harvest with published datasets that deregistering will make it impossible to bulk-revert the datasets connected to it (maybe actually displaying a list of them?). But we must have gotten distracted before making a new PR.

@janette or @jastraat do you know any other details about this? If my memory is more or less correct we would accept a PR from you along those lines @stefan-korn or might have time to redo it on our end soon (can't guarantee a timeline though).

**Comment by stefan-korn** [comment]
@dafeder : Okay, removing the revert from the deregister command seems feasible to me. Will try to provide a PR for that. 

Should this issue be opened again?

**Comment by dafeder** [comment]
The issue (#3839) is still open

**Pull request closed without merging**
