### PR TITLE
Add an example on how to set the dkan_map_tile_url variable

### PR DESCRIPTION
**Pull request by janette**
Small improvement to docs to call out new functionality

### CODE REVIEW

**Comment by janette** [comment]
The phpunit test that fails needs to be revamped, will create a new ticket for that.

**Comment by acouch** [comment]
I can merge once tests pass.

**Comment by janette** [comment]
@acouch this is a change in documentation not functionality

**Comment by acouch** [comment]
I know but why are tests failing on this PR?

**Comment by janette** [comment]
the test was fixed on another PR, I will rebase

**Pull request merged**
