### PR TITLE
Removal of percentages from fetch/import jobs and dashboard

### PR DESCRIPTION
**Pull request by kaise-lafrai**
fixes [org/repo/WCMS-11950]

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Pull branch down to your local for testing
- [ ] Create new dataset @ /node/add/data
- [ ] Navigate to dashboard @ /admin/dkan/datastore/status
- [ ] Confirm new row exists for the new dataset
- [ ] Confirm **Fetch** column displays status only and does _not_ display the percentage done
- [ ] Confirm **Store** column displays status only and does _not_ display the percentage done
- [ ] VIA terminal run the following drush command `ddev drush dkan:datastore:list`
- [ ] Confirm that the **FileFetcher** and **Importer** columns do _not_ display percentages done.
- [ ] Run `ddev dkan-phpunit` and confirm tests pass.

### CODE REVIEW

**Comment by jastraat** [comment]
I thought we were going to leave the import percentage complete since that is used by PDC since we're still using the chunking importer...?

**Comment by kaise-lafrai** [comment]
> I thought we were going to leave the import percentage complete since that is used by PDC since we're still using the chunking importer...?

I should probably close this PR since we decided not to remove the percentages. Thanks @jastraat

**Comment by jastraat** [comment]
Just to add this here, our team used the import percentages just last week -

**Comment by dafeder** [comment]
We returned to this issue and addressed it differently in #4181. Closing.

**Pull request closed without merging**
