### PR TITLE
Convert http:// to https:// where appropriate

### PR DESCRIPTION
**Pull request by janette**
Connects #2373

### CODE REVIEW

**Comment by janette** [comment]
@openprivacy yes still a WIP

**Comment by openprivacy** [comment]
Approximately one-third (250 of 793) of the HTTP protocol instances were updated to HTTPS. There are a good number remaining, notably `healthdata.gov`, `drupal.org` and `www.google.com`. Below is an imperfect script that found these and about 80 others (though it unfortunately returns some false positives) -- the question is: how complete should we be (to consider this ticket complete)?
```
# run from dkan dir with branch `33-https` pulled:
SITES=$(grep -r http:// . | grep -v 'Binary file' | sed 's/.*http:\/\/\([a-z\-]*\.[a-z\.]*\).*$/\1/' | sort | uniq | egrep -v '(:|www.w|www.open|yoursite.com|civicinsights.org|data.g|data.mosreg.ru|data.telangana.gov.in|dati.comune.genova.it|datos.concytec.gob.pe|datoselsalvador.org|datos.imss.gob.mx|datos.minsa.gob.pe|everzet.com|guzzlephp.org|j.mp|miamidadempo.org|nuams.com|nucivic.com|odwe.ca|opendata.pa|opendata.gov.sl|tylerfrankenstein.com|udfr.org)')

for SITE in $SITES; do
  $(echo Q | openssl s_client -connect ${SITE}:443 2>/dev/null | grep -q "TLS session ticket") && echo $SITE
done
```

I have not checked the code for lint or with PHP_CodeSniffer though I see you've done some linting. Do you have a suggestion as to how to better QA this ticket?

**Comment by janette** [comment]
@openprivacy I ran the code you provided above and it creates a list of domains..., not sure what you want me to do with that. I'm curious where you are finding 793 instances of http://, are you excluding the **contrib** and **libraries** directories?

**Comment by openprivacy** [comment]
@janette Take a look at the commands at the top of #2373 :
- Running the count command in the cloned DKAN repo returned 793 instances of `http://` (no Drupal, no `contrib`, no `libraries`).
- Running the same command in the new `1.14` branch returns 768 instances, and in the `33-https` branch it's down to 543 (250 less than the original 793):
```
$ git co 1.14
Branch '1.14' set up to track remote branch '1.14' from 'origin' by rebasing.
Switched to a new branch '1.14'
$ grep -r http:// . | grep -v 'Binary file'  | wc -l
768
$ git co 33-https
Switched to branch '33-https'
Your branch is up to date with 'origin/33-https'.
$ grep -r http:// . | grep -v 'Binary file'  | wc -l
543
```

The commands in the above comment feed these sites into `openssl` in an imperfect attempt to find sites returning a `TLS session ticket` and thus likely to have HTTPS configured. These are sites that still have `http://` in the DKAN code base but (probably) use HTTPS and therefore should be referenced with `https://`. For example:
```
$ grep -r healthdata.gov .
./docs/community/opendatastandards.rst:The screencap below is an example of metadata for the "Safety Net Clinics" dataset on `HealthData.gov <http://www.healthdata.gov/>`_:
./docs/community/opendatastandards.rst:*Source: ** http://www.healthdata.gov/dataset/safety-net-clinics
./docs/introduction/dkan-sites.rst:U.S. Department of Health and Human Services (USA)      http://healthdata.gov
```

We can chat Tuesday (or anytime) if you have questions.

**Comment by janette** [comment]
dkan/modules/dkan
```
$grep -r http:// dkan | grep -v 'Binary file' | sed 's/.*\(http:\/\/[^\/]*\).*$/\1/' | sort | uniq -c | sort -nr | head -20
  92 http://default
  18 http://opendefinition.org
  13 http://demo.getdkan.com
  10 http://example.com
   5 http://www.agency.gov
   5 http://') {
   3 http://opendefinition.org">opendefinition.org<
   2 http://purl.org
   2 http://miamidadempo.org
   2 http://la.streetsblog.org
   2 http://blog.concentra.co.uk
   1 http://www.lfpress.com
   1 http://tylerfrankenstein.com
   1 http://statehealthfacts.org
   1 http://oneclick.cartodb.com
   1 http://geographicdata.slocity.opendata.arcgis.com
   1 http://example.com).');
   1 http://dx.doi.org
   1 http://docs.ckan.org
   1 http://demo.ckan.org
```
dkan/docs
```
grep -r http:// docs | grep -v 'Binary file' | sed 's/.*\(http:\/\/[^\/]*\).*$/\1/' | sort | uniq -c | sort -nr | head -20
  18 http://docker:32774
  12 http://demo.getdkan.com
  11 http://docs.ckan.org
   5 http://EXAMPLE.COM
   4 http://example.com
   2 http://www.sphinx-doc.org
   2 http://transformagriculture.org
   2 http://standard.open-contracting.org
   2 http://cove.opendataservices.coop
   1 http://yoursite.com
   1 http://www.w3schools.com
   1 http://www.voteswithoutviolence.org
   1 http://www.streamlineicons.com
   1 http://www.openstreetmap.org
   1 http://www.opendatafoundation.org
   1 http://www.namopendata.com
   1 http://www.flaticon.com
   1 http://www.fgdc.gov
   1 http://www.drush.org
   1 http://www.dcat.be
```

**Comment by janette** [comment]
@openprivacy if you have time today lets chat about this ticket

**Pull request merged**
