### PR TITLE
Allow state select leaftlet

### PR DESCRIPTION
**Pull request by jacintocapote**
ref: NuCivic/internal#865

We added two new utilities to leaflet widget:
  1.- On the settings field you can select to show use a list select with predefined states or regions. This is implemented with hook that other modules can extend (You need to enable leaflet_widget_us to show USA states on the list. After enable the checkbox on the field you can see the list on the map.
2.- Added new option for points and you can add a lat, long.

You should see the similar to the attachment page.
north dakota gis data

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://allow_state_select_leaftlet.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://allow_state_select_leaftlet.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://allow_state_select_leaftlet.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
We added two new utilities to leaflet widget:
  1.- On the settings field you can select to show use a list select with predefined states or regions. This is implemented with hook that other modules can extend (You need to enable leaflet_widget_us to show USA states on the list. After enable the checkbox on the field you can see the list on the map.
2.- Added new option for points and you can add a lat, long.

You should see the similar to the attachment page.
north dakota gis data

**Comment by nucivicmachine** [comment]
QA site created: http://allow_state_select_leaftlet.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Actual PR: NuCivic/dkan_dataset#148

**Comment by kimwdavidson** [comment]
Current implementation is too US-specific for this feature, need a way for people to supply their own outlines. Adding to the Icebox for historical documentation. Anyone can use this code as a starting point for creating their own custom version.

**Comment by dafeder** [comment]
This PR isn't usable anymore, going to open an issue to deal with it.

**Pull request closed without merging**
