### PR TITLE
Add release script and Jenkinsfile

### PR DESCRIPTION
**Pull request by dafeder**
To start doing automatic packaging of DKAN on releases, adding a Jenkinsfile and php packaging script. Adds version info and removes scripts and docs for a downloadable release. (Note: removing the docs is new; we can remove this but I don't think we really need to be distributing them with the releases.)

Also creates a PR for a DROPS release

## QA Steps

The asset files uploaded to the [jenkins20](https://github.com/GetDKAN/dkan/releases/tag/jenkins20) release were automatically generated and uploaded. Check the files and confirm they look as expected.

Check GetDKAN/dkan-drops-7#95, generated by the same tag

## Merging instructions

Delete any "jenkins*" releases and tags from the github repo.
Delete GetDKAN/dkan-drops-7#95

### CODE REVIEW

**Comment by dafeder** [comment]
@janette assigned to you but may want @woodt to take a look

**Comment by janette** [comment]
@dafeder is there a way to create a dkan-drops-7 PR without creating a tag on dkan?

**Comment by dafeder** [comment]
Mmm - not currently, did not realize that was needed. When do we do that?

**Comment by janette** [comment]
@dafeder what would be the steps to create 7.x-1.17.4 and 7.x-1.17.0 drops PRs

**Comment by janette** [comment]
Also need to switch to PAT for nucivicmachine

> Hi @nucivicmachine,

> You recently used a password to access an endpoint through the GitHub API using okhttp/2.7.5. We will deprecate basic authentication using password to this endpoint soon:

> https://api.github.com/user

> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

> Thanks,
> The GitHub Team

**Comment by dafeder** [comment]
@woodt can you give me an example of the kinds of dependencies I'd need to document? I'm not sure what we have in the jenkins server that's non-standard...

**Comment by dafeder** [comment]
Updated, see changes at 81416257691ba655eeaf3bd71d8c3b381fa66c48, [build result](https://jenkins.ci.civicactions.net/job/DKAN/job/DKAN%20Main%20Repo/job/jenkins30/) and resulting PR: GetDKAN/dkan-drops-7#97

**Comment by woodt** [comment]
@dafeder W.R.T. dependencies, I was thinking more of external components/services (other than the GetDKAN/dkan repo.)  So , maybe like:

- Uses the GitHub API to create pull requests ...
- Depends on the pantheon-system and GetDKAN/dkan-drops-7 repos
- Uses the getdkan/dkan-docker:php72-cli image

Obviously,  one could read the script(s) to discover all of this, but my thought was to let someone look at the comment and quickly understand dependencies on external systems w/o having to do so.

**Comment by dafeder** [comment]
@woodt better? :smile:

**Pull request merged**
